#pragma checksum "..\..\..\..\MainWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "12E7091E619F17E7E1DB369550C89140DD3AE5CC"
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using SIRASD.Desktop;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace SIRASD.Desktop {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 6 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid LoginView;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EmailBox;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox PasswordBox;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LoginError;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid ApplicationView;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SidebarMonogram;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SidebarCenterName;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button HomeNav;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button PatientsNav;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button PaymentsNav;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BedsNav;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button MedicationsNav;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel ExtraNavigation;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BackupsNav;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SignedUser;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CenterBreadcrumb;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PageTitle;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PageSubtitle;
        
        #line default
        #line hidden
        
        
        #line 81 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CurrentDate;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid DashboardPanel;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock WelcomeTitle;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ActivePatientsText;
        
        #line default
        #line hidden
        
        
        #line 97 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock OccupiedBedsText;
        
        #line default
        #line hidden
        
        
        #line 98 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock AvailableBedsText;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock IncidentsText;
        
        #line default
        #line hidden
        
        
        #line 104 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CapacityText;
        
        #line default
        #line hidden
        
        
        #line 104 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock OccupancyText;
        
        #line default
        #line hidden
        
        
        #line 104 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ProgressBar OccupancyBar;
        
        #line default
        #line hidden
        
        
        #line 114 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PatientsPanel;
        
        #line default
        #line hidden
        
        
        #line 117 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PatientSearch;
        
        #line default
        #line hidden
        
        
        #line 123 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid PatientsGrid;
        
        #line default
        #line hidden
        
        
        #line 130 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal SIRASD.Desktop.PaymentsView PaymentsPanel;
        
        #line default
        #line hidden
        
        
        #line 131 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid BedsPanel;
        
        #line default
        #line hidden
        
        
        #line 136 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid BedsGrid;
        
        #line default
        #line hidden
        
        
        #line 140 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal SIRASD.Desktop.MedicationsView MedicationsPanel;
        
        #line default
        #line hidden
        
        
        #line 141 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ContentControl CenterPanel;
        
        #line default
        #line hidden
        
        
        #line 142 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid BackupsPanel;
        
        #line default
        #line hidden
        
        
        #line 150 "..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StatusText;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.12.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/SIRASD;V0.9.7.0;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.12.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.12.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.LoginView = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.EmailBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.PasswordBox = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 35 "..\..\..\..\MainWindow.xaml"
            this.PasswordBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.PasswordBox_KeyDown);
            
            #line default
            #line hidden
            return;
            case 4:
            this.LoginError = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            
            #line 37 "..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Login_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            
            #line 38 "..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CreateAccount_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.ApplicationView = ((System.Windows.Controls.Grid)(target));
            return;
            case 8:
            this.SidebarMonogram = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.SidebarCenterName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.HomeNav = ((System.Windows.Controls.Button)(target));
            
            #line 54 "..\..\..\..\MainWindow.xaml"
            this.HomeNav.Click += new System.Windows.RoutedEventHandler(this.Navigation_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.PatientsNav = ((System.Windows.Controls.Button)(target));
            
            #line 55 "..\..\..\..\MainWindow.xaml"
            this.PatientsNav.Click += new System.Windows.RoutedEventHandler(this.Navigation_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.PaymentsNav = ((System.Windows.Controls.Button)(target));
            
            #line 56 "..\..\..\..\MainWindow.xaml"
            this.PaymentsNav.Click += new System.Windows.RoutedEventHandler(this.Navigation_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.BedsNav = ((System.Windows.Controls.Button)(target));
            
            #line 57 "..\..\..\..\MainWindow.xaml"
            this.BedsNav.Click += new System.Windows.RoutedEventHandler(this.Navigation_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.MedicationsNav = ((System.Windows.Controls.Button)(target));
            
            #line 58 "..\..\..\..\MainWindow.xaml"
            this.MedicationsNav.Click += new System.Windows.RoutedEventHandler(this.Navigation_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.ExtraNavigation = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 16:
            this.BackupsNav = ((System.Windows.Controls.Button)(target));
            
            #line 60 "..\..\..\..\MainWindow.xaml"
            this.BackupsNav.Click += new System.Windows.RoutedEventHandler(this.Navigation_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.SignedUser = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 18:
            
            #line 68 "..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Navigation_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            
            #line 69 "..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Profile_Click);
            
            #line default
            #line hidden
            return;
            case 20:
            
            #line 70 "..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Logout_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.CenterBreadcrumb = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 22:
            this.PageTitle = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 23:
            this.PageSubtitle = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 24:
            this.CurrentDate = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 25:
            this.DashboardPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 26:
            this.WelcomeTitle = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 27:
            this.ActivePatientsText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 28:
            this.OccupiedBedsText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 29:
            this.AvailableBedsText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 30:
            this.IncidentsText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 31:
            this.CapacityText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 32:
            this.OccupancyText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 33:
            this.OccupancyBar = ((System.Windows.Controls.ProgressBar)(target));
            return;
            case 34:
            
            #line 104 "..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Navigation_Click);
            
            #line default
            #line hidden
            return;
            case 35:
            
            #line 107 "..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NewPatient_Click);
            
            #line default
            #line hidden
            return;
            case 36:
            
            #line 107 "..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Navigation_Click);
            
            #line default
            #line hidden
            return;
            case 37:
            this.PatientsPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 38:
            this.PatientSearch = ((System.Windows.Controls.TextBox)(target));
            
            #line 117 "..\..\..\..\MainWindow.xaml"
            this.PatientSearch.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.PatientSearch_TextChanged);
            
            #line default
            #line hidden
            return;
            case 39:
            
            #line 118 "..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.WhatsAppPatient_Click);
            
            #line default
            #line hidden
            return;
            case 40:
            
            #line 118 "..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.EditPatient_Click);
            
            #line default
            #line hidden
            return;
            case 41:
            
            #line 118 "..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NewPatient_Click);
            
            #line default
            #line hidden
            return;
            case 42:
            this.PatientsGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 123 "..\..\..\..\MainWindow.xaml"
            this.PatientsGrid.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.Patient_DoubleClick);
            
            #line default
            #line hidden
            return;
            case 43:
            this.PaymentsPanel = ((SIRASD.Desktop.PaymentsView)(target));
            return;
            case 44:
            this.BedsPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 45:
            this.BedsGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 46:
            this.MedicationsPanel = ((SIRASD.Desktop.MedicationsView)(target));
            return;
            case 47:
            this.CenterPanel = ((System.Windows.Controls.ContentControl)(target));
            return;
            case 48:
            this.BackupsPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 49:
            
            #line 145 "..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CreateBackup_Click);
            
            #line default
            #line hidden
            return;
            case 50:
            
            #line 146 "..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ImportBackup_Click);
            
            #line default
            #line hidden
            return;
            case 51:
            this.StatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

