#pragma checksum "..\..\..\..\MedicationsView.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0B0094E1F6104472B5BDDFA06A7C03F5A8853062"
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace SIRASD.Desktop {
    
    
    /// <summary>
    /// MedicationsView
    /// </summary>
    public partial class MedicationsView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 23 "..\..\..\..\MedicationsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LotsText;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\MedicationsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LowStockText;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\MedicationsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ExpiryText;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\MedicationsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button InventoryTab;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\MedicationsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button HistoryTab;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\..\MedicationsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid InventoryPanel;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\..\MedicationsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InventorySearch;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\MedicationsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox StockFilter;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\MedicationsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid InventoryGrid;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\..\MedicationsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SelectedMedicationText;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\..\MedicationsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ReceiveButton;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\..\MedicationsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SupplyButton;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\..\MedicationsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button LossButton;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\..\MedicationsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid HistoryPanel;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\..\MedicationsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox HistorySearch;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\..\MedicationsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox MovementFilter;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\..\MedicationsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker FromDate;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\..\MedicationsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker ToDate;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\..\..\MedicationsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid HistoryGrid;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\..\MedicationsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock FeedbackText;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.12.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/SIRASD;V0.9.7.0;component/medicationsview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\MedicationsView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.12.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.LotsText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.LowStockText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.ExpiryText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.InventoryTab = ((System.Windows.Controls.Button)(target));
            
            #line 28 "..\..\..\..\MedicationsView.xaml"
            this.InventoryTab.Click += new System.Windows.RoutedEventHandler(this.InventoryTab_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.HistoryTab = ((System.Windows.Controls.Button)(target));
            
            #line 28 "..\..\..\..\MedicationsView.xaml"
            this.HistoryTab.Click += new System.Windows.RoutedEventHandler(this.HistoryTab_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            
            #line 29 "..\..\..\..\MedicationsView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Charts_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            
            #line 29 "..\..\..\..\MedicationsView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Refresh_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.InventoryPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 9:
            this.InventorySearch = ((System.Windows.Controls.TextBox)(target));
            
            #line 35 "..\..\..\..\MedicationsView.xaml"
            this.InventorySearch.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.Filter_Changed);
            
            #line default
            #line hidden
            return;
            case 10:
            this.StockFilter = ((System.Windows.Controls.ComboBox)(target));
            
            #line 36 "..\..\..\..\MedicationsView.xaml"
            this.StockFilter.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.Filter_Changed);
            
            #line default
            #line hidden
            return;
            case 11:
            
            #line 39 "..\..\..\..\MedicationsView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NewMedication_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.InventoryGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 44 "..\..\..\..\MedicationsView.xaml"
            this.InventoryGrid.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.Inventory_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 13:
            this.SelectedMedicationText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            this.ReceiveButton = ((System.Windows.Controls.Button)(target));
            
            #line 63 "..\..\..\..\MedicationsView.xaml"
            this.ReceiveButton.Click += new System.Windows.RoutedEventHandler(this.Receive_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.SupplyButton = ((System.Windows.Controls.Button)(target));
            
            #line 63 "..\..\..\..\MedicationsView.xaml"
            this.SupplyButton.Click += new System.Windows.RoutedEventHandler(this.Supply_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.LossButton = ((System.Windows.Controls.Button)(target));
            
            #line 63 "..\..\..\..\MedicationsView.xaml"
            this.LossButton.Click += new System.Windows.RoutedEventHandler(this.Loss_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.HistoryPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 18:
            this.HistorySearch = ((System.Windows.Controls.TextBox)(target));
            
            #line 69 "..\..\..\..\MedicationsView.xaml"
            this.HistorySearch.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.Filter_Changed);
            
            #line default
            #line hidden
            return;
            case 19:
            this.MovementFilter = ((System.Windows.Controls.ComboBox)(target));
            
            #line 70 "..\..\..\..\MedicationsView.xaml"
            this.MovementFilter.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.Filter_Changed);
            
            #line default
            #line hidden
            return;
            case 20:
            this.FromDate = ((System.Windows.Controls.DatePicker)(target));
            
            #line 72 "..\..\..\..\MedicationsView.xaml"
            this.FromDate.SelectedDateChanged += new System.EventHandler<System.Windows.Controls.SelectionChangedEventArgs>(this.Filter_Changed);
            
            #line default
            #line hidden
            return;
            case 21:
            this.ToDate = ((System.Windows.Controls.DatePicker)(target));
            
            #line 72 "..\..\..\..\MedicationsView.xaml"
            this.ToDate.SelectedDateChanged += new System.EventHandler<System.Windows.Controls.SelectionChangedEventArgs>(this.Filter_Changed);
            
            #line default
            #line hidden
            return;
            case 22:
            
            #line 72 "..\..\..\..\MedicationsView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ClearFilters_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            this.HistoryGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 74 "..\..\..\..\MedicationsView.xaml"
            this.HistoryGrid.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.History_DoubleClick);
            
            #line default
            #line hidden
            return;
            case 24:
            
            #line 90 "..\..\..\..\MedicationsView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Detail_Click);
            
            #line default
            #line hidden
            return;
            case 25:
            this.FeedbackText = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

