#pragma checksum "..\..\..\..\MedicationMovementDialog.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "1869D877F1CFC5DCA875E18B151BB07FF827FDD1"
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace SIRASD.Desktop {
    
    
    /// <summary>
    /// MedicationMovementDialog
    /// </summary>
    public partial class MedicationMovementDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 6 "..\..\..\..\MedicationMovementDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock HeadingText;
        
        #line default
        #line hidden
        
        
        #line 6 "..\..\..\..\MedicationMovementDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock MedicationText;
        
        #line default
        #line hidden
        
        
        #line 6 "..\..\..\..\MedicationMovementDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StockText;
        
        #line default
        #line hidden
        
        
        #line 8 "..\..\..\..\MedicationMovementDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel PatientFields;
        
        #line default
        #line hidden
        
        
        #line 8 "..\..\..\..\MedicationMovementDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox PatientBox;
        
        #line default
        #line hidden
        
        
        #line 10 "..\..\..\..\MedicationMovementDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock QuantityLabel;
        
        #line default
        #line hidden
        
        
        #line 10 "..\..\..\..\MedicationMovementDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox QuantityBox;
        
        #line default
        #line hidden
        
        
        #line 11 "..\..\..\..\MedicationMovementDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ResponsibleBox;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\..\..\MedicationMovementDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker DateBox;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\..\..\MedicationMovementDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TimeBox;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\..\MedicationMovementDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ReferenceLabel;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\..\MedicationMovementDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ReferenceBox;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\..\MedicationMovementDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock NotesLabel;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\..\MedicationMovementDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox NotesBox;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\..\MedicationMovementDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock RecordedByText;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\MedicationMovementDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ValidationText;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\MedicationMovementDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SaveButton;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.12.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/SIRASD;V0.9.7.0;component/medicationmovementdialog.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\MedicationMovementDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.12.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.HeadingText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.MedicationText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.StockText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.PatientFields = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 5:
            this.PatientBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 6:
            this.QuantityLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.QuantityBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.ResponsibleBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.DateBox = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 10:
            this.TimeBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.ReferenceLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.ReferenceBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.NotesLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            this.NotesBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 15:
            this.RecordedByText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 16:
            this.ValidationText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.SaveButton = ((System.Windows.Controls.Button)(target));
            
            #line 24 "..\..\..\..\MedicationMovementDialog.xaml"
            this.SaveButton.Click += new System.Windows.RoutedEventHandler(this.Save_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

